spring.application.name=gibackend

## github aes auth token
github.aes.auth-token = oMLGVMLbC+Hko7Mf91vrqJhO/ng0gyXODlg3dlCD5NBbSJyHco2vgrRSigHGd3Z8

## github integration url
github.api-url-getUser=https://api.github.com/users


